spring:
    application:
        name: Spring workout
    datasource:
        url: 'jdbc:postgresql://localhost:5432/spring-workout'
        username: postgres
        password: admin
    data:
        rest:
            base-path: /api

    liquibase:
        change-log: 'classpath:db/changelog/db-changelog.xml'